#
# Source code address
# https://hub.docker.com/u/cuongtransc/
#
# syntax: https://docs.docker.com/compose/compose-file/
#

version: "2"

services:

    wordpress:
        image: wordpress:4.5
        links:
            - mariadb:mysql
        ports:
            - "80:80"
        networks:
            - back-tier
        environment:
            - WORDPRESS_DB_HOST=mysql
            - WORDPRESS_DB_USER=wordpress
            - WORDPRESS_DB_PASSWORD=wordpress@123
            - WORDPRESS_DB_NAME=wordpress
        hostname: wordpress
        domainname: coclab.lan
        cpu_shares: 512             # 0.5 CPU
        mem_limit: 536870912        # 512 MB RAM
        # privileged: true
        # restart: on-failure:3     # other choice: always
        # stdin_open: true
        # tty: true

    mariadb:
        image: mariadb:10.1
        #ports:
            #- "3306:3306"
        networks:
            - back-tier
        volumes:
            - ./mariadb-data/:/var/lib/mysql/
        environment:
            - MYSQL_ROOT_PASSWORD=lab@secret
            - MYSQL_USER=wordpress
            - MYSQL_PASSWORD=wordpress@123
            - MYSQL_DATABASE=wordpress
        hostname: mariadb
        domainname: coclab.lan
        cpu_shares: 512             # 0.5 CPU
        mem_limit: 536870912        # 512 MB RAM
        # privileged: true
        # restart: on-failure:3     # other choice: always
        # stdin_open: true
        # tty: true

networks:
    back-tier:

# volumes:
#     db-data:
